name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [ "master", "develop**", "release**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev python3-distutils libfastjson-dev libcurl4-gnutls-dev libssl-dev

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/home/runner/work/access/build/ext_install
          make -j8

